/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Person_Nhanvien;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class Fnhap extends javax.swing.JFrame {

    //bước 1 : khai bao
    private List<NhanVien> dsnhanvien = new ArrayList<>();

    /**
     * Creates new form Fnhap
     */
    public Fnhap() {
        initComponents();
        cauhinhcombobox();

    }

    private void cauhinhcombobox() {
        cbo_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Nam", "Nữ", "khác"}));
        cbo_phongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Thiết bị", "Nhân sự", "R&D", "Kinh doanh"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ngaysinh = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_hesoluong = new javax.swing.JTextField();
        txt_thamnien = new javax.swing.JTextField();
        txt_luongcoban = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        cbo_gioitinh = new javax.swing.JComboBox<>();
        cbo_phongban = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_luongthuclinh = new javax.swing.JTextField();
        btn_tinhluong = new javax.swing.JButton();
        btn_hienthi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField7.setText("jTextField1");

        jTextField8.setText("jTextField1");

        cbo_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_phongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lưu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("nhập họ tên");

        jLabel2.setText("nhập ngày sinh");

        jLabel3.setText("địa chỉ");

        jLabel4.setText("hệ số lương");

        jLabel5.setText("thâm niên");

        jLabel6.setText("lương cơ bản");

        txt_luongthuclinh.setText("lương thực lĩnh");

        btn_tinhluong.setText("Tính lương");
        btn_tinhluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tinhluongActionPerformed(evt);
            }
        });

        btn_hienthi.setText("Hiển thị nhân viên");
        btn_hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btn_hienthi)
                .addGap(223, 223, 223))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txt_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_diachi)
                                        .addComponent(txt_ngaysinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbo_gioitinh, 0, 334, Short.MAX_VALUE)
                                        .addComponent(cbo_phongban, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_hesoluong))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btn_tinhluong, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_luongthuclinh))
                                        .addComponent(txt_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(565, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(555, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(cbo_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbo_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tinhluong)
                    .addComponent(txt_luongthuclinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(btn_hienthi))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //1 lấy data từ design
            String ht = txt_hoten.getText().toString().trim();
            String ns = txt_ngaysinh.getText().toString().trim();
            String dc = txt_diachi.getText().toString().trim();
            String gt = (String) cbo_gioitinh.getSelectedItem();
            String pb = (String) cbo_phongban.getSelectedItem();

            if (ht.isEmpty() || ns.isEmpty() || dc.isEmpty() || gt.isEmpty() || pb.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "vui lòng nhập đủ thông tin họ tên , ngày sinh , địa chỉ , giới tính  , phòng ban");
                return;
            }

            float hsl = Float.parseFloat(txt_hesoluong.getText().toString().trim());
            float tn = Float.parseFloat(txt_thamnien.getText().toString().trim());
            float lcb = Float.parseFloat(txt_luongcoban.getText().toString().trim());

            if (hsl <= 0 || tn < 0 || lcb <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Hệ số lương và lương cơ bản phải > 0\nThâm niên phải >= 0");
                return;
            }
             //tạo một đối tượng nhân viên
            NhanVien newnv = new NhanVien(ht, ns, dc, gt, pb, hsl, tn, lcb);
            dsnhanvien.add(newnv);
            
            javax.swing.JOptionPane.showMessageDialog(this, "nhân viên đã được thêm là: " + newnv.hienthinhanvien());
            System.err.println("thêm nhân viên thành công ");
            System.err.println("nhân viên là" + newnv.hienthinhanvien());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "vui lòng nhập đúng định dạng hệ số lương , thâm niên , lương cơ bản");

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //tạo file 
        try {
            File file = new File("C:/file/nhanvien.dat");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            if (dsnhanvien.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "vui lòng thêm nhân viên trước");
                return;
            }

            for (NhanVien nv : dsnhanvien) {
                bw.write(nv.getHoten() + "$"
                        + nv.getNgaysinh() + "$"
                        + nv.getDiachi() + "$"
                        + nv.getGioitinh() + "$"
                        + nv.getPhongban() + "$"
                        + nv.getHesoluong() + "$"
                        + nv.getThamnien() + "$"
                        + nv.getLuongcoban() + "$"
                        + nv.luongthuclinh());
                bw.newLine();
            }
            xoahienthi();
            bw.close();
            fw.close();
            javax.swing.JOptionPane.showMessageDialog(this, "lưu file thành công tại đường dẫn: C:/file/nhanvien.dat");
            System.err.println("đã được lưu");
        } catch (Exception e) {
            System.err.println("lỗi ghi file");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_tinhluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tinhluongActionPerformed

        try {
            if (txt_hesoluong.getText().trim().isEmpty()
                    || txt_thamnien.getText().trim().isEmpty()
                    || txt_luongcoban.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ hệ số lương, thâm niên và lương cơ bản");
                return;
            }

            float hsl = Float.parseFloat(txt_hesoluong.getText().trim());
            float tn = Float.parseFloat(txt_thamnien.getText().trim());
            float lcb = Float.parseFloat(txt_luongcoban.getText().trim());

            if (hsl <= 0 || tn < 0 || lcb <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Hệ số lương và lương cơ bản phải > 0\nThâm niên phải >= 0");
                return;
            }

            float ltl = lcb * hsl * (1 + tn / 100);

            txt_luongthuclinh.setText(String.format(ltl + " VNĐ"));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "vui lòng nhập đúng định dạng hệ số lương , thâm niên , lương cơ bản");
        }
    }//GEN-LAST:event_btn_tinhluongActionPerformed

    private void btn_hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienthiActionPerformed

        Ftable_hienthi frmhienthi = new Ftable_hienthi();
        frmhienthi.setVisible(true);
    }//GEN-LAST:event_btn_hienthiActionPerformed

    private void xoahienthi() {
        txt_hoten.setText("");
        txt_ngaysinh.setText("");
        txt_diachi.setText("");
        txt_hesoluong.setText("");
        txt_thamnien.setText("");
        txt_luongcoban.setText("");
        cbo_gioitinh.setSelectedIndex(0);
        cbo_phongban.setSelectedIndex(0);
        txt_hoten.requestFocus();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hienthi;
    private javax.swing.JButton btn_tinhluong;
    private javax.swing.JComboBox<String> cbo_gioitinh;
    private javax.swing.JComboBox<String> cbo_phongban;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_hesoluong;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_luongcoban;
    private javax.swing.JTextField txt_luongthuclinh;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_thamnien;
    // End of variables declaration//GEN-END:variables
}
