/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Person_Student;

import Person_Nhanvien.NhanVien;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class hienthisinhvien extends javax.swing.JFrame {
    
    private DefaultTableModel tablemodel;

    /**
     * Creates new form hienthisinhvien
     */
    public hienthisinhvien() {
        initComponents();
        tablemodel = (DefaultTableModel) table_sinhvien.getModel();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_sinhvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "masinhvien", "email", "diemtongket", "hoten", "ngaysinh", "diachi", "gioitinh"
            }
        ));
        jScrollPane1.setViewportView(table_sinhvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hienthisinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hienthisinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hienthisinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hienthisinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hienthisinhvien().setVisible(true);
            }
        });
    }
    
    private List<Student> docfilesinhvien(String duongdan) {
        List<Student> danhsachsinhvien = new ArrayList<>();
        
        File file = new File(duongdan);
        
        try {
            FileReader fw = new FileReader(file);
            BufferedReader br = new BufferedReader(fw);
            
            String line = " ";
            
            while ((line = br.readLine()) != null) {
                
                String[] part = line.split("\\$");
                
                if (part.length == 7) {
                    String msv = part[0];
                    String email = part[1];
                    Float diemtongket = Float.parseFloat(part[2]);
                    String hoten = part[3];
                    String ngaysinh = part[4];
                    String diachi = part[5];
                    String gioitinh = part[6];
                    
                    Student st = new Student(msv, email, diemtongket, hoten, ngaysinh, diachi, gioitinh);
                    danhsachsinhvien.add(st);
                }
                
            }
            br.close();
            fw.close();
        } catch (Exception e) {
            e.getStackTrace();
            System.err.print(" đọc file thất bại");
        }
        
        return danhsachsinhvien;
    }
    
    private void load_table() {
        List<Student> dsst = docfilesinhvien("C:/file/student.dat");
        
        for (Student st : dsst) {
            tablemodel.addRow(new Object[]{
                st.getMasinhvien(),
                st.getEmail(),
                st.getDiemtongket(),
                st.getHoten(),
                st.getNgaysinh(),
                st.getDiachi(),
                st.getGioitinh()
            }
            );
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_sinhvien;
    // End of variables declaration//GEN-END:variables
}
